import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";

const FigtreeFont = Figtree({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LaunchDeck",
  description: "Generated by LaunchDeck",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${FigtreeFont.className} h-full antialiased`}
    >
      <body className="relative min-h-screen bg-slate-950 text-white">

        {/* GLOBAL BACKGROUND SYSTEM */}
        <div className="pointer-events-none fixed inset-0 z-0">
          {/* Persistent Subtle Grid Layout */}
          <div className="absolute inset-0 bg-[linear-gradient(to_right,#33415512_1px,transparent_1px),linear-gradient(to_bottom,#33415510_1px,transparent_1px)] bg-[size:4rem_4rem]" />

          {/* Ambient Corner Glow Spots */}
          <div className="absolute -top-40 left-0 h-[500px] w-[500px] rounded-full bg-blue-600/10 blur-[140px]" />
          <div className="absolute bottom-10 right-0 h-[600px] w-[600px] rounded-full bg-emerald-500/10 blur-[140px]" />
        </div>

        {/* APPLICATION WRAPPER */}
        <div className="relative z-10 flex min-h-screen flex-col">
          <Navbar />
          <main className="flex-1">
            {children}
          </main>
        </div>

      </body>
    </html>
  );
}